/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package humanizar.alquilerprendas.view;

import humanizar.alquilerprendas.controller.LoginController;
import humanizar.alquilerprendas.controller.ProductoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres Santos
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ProductoController prodContoller = new ProductoController();
    public int id;
    public home(int idUser) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        System.out.println(idUser);
        this.id=idUser;
        jtPrendas.setModel(prodContoller.cargarProductos(null, null, null, null, null));

    }

    public String obtenerFiltro(JComboBox combo) {
        Object item = combo.getSelectedItem();
        if (item != null && !item.toString().equalsIgnoreCase("Seleccione un tipo")) {
            return item.toString();
        }
        return null;
    }

    LoginController login = new LoginController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BtnAlquilar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnFiltros = new javax.swing.JPanel();
        BtnFiltro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FiltroTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FiltroTalla = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        FiltroMaterial = new javax.swing.JComboBox<>();
        FiltroGenero = new javax.swing.JComboBox<>();
        labelGenero = new javax.swing.JLabel();
        FiltroCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        QuitarFiltros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrendas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 350));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setMaximumSize(new java.awt.Dimension(1500, 580));
        jPanel3.setMinimumSize(new java.awt.Dimension(1500, 580));
        jPanel3.setPreferredSize(new java.awt.Dimension(1500, 580));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAlquilar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAlquilar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlquilar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAlquilar.setText("ALQUILAR");
        BtnAlquilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAlquilarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAlquilar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAlquilar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALIR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 1100, 90));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnFiltros.setBackground(new java.awt.Color(102, 102, 102));
        BtnFiltros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnFiltro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnFiltro.setForeground(new java.awt.Color(255, 255, 255));
        BtnFiltro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnFiltro.setText("FILTRAR");
        BtnFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFiltroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BtnFiltrosLayout = new javax.swing.GroupLayout(BtnFiltros);
        BtnFiltros.setLayout(BtnFiltrosLayout);
        BtnFiltrosLayout.setHorizontalGroup(
            BtnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BtnFiltrosLayout.setVerticalGroup(
            BtnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPanel1.add(BtnFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 443, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FILTROS");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 160, 76));

        FiltroTipo.setBackground(new java.awt.Color(153, 153, 153));
        FiltroTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroTipo.setForeground(new java.awt.Color(255, 255, 255));
        FiltroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Casual", "Formal", "Deportivo", "Fiesta", "Boda", "Trabajo", "Playa", "Invierno", "Verano", "Urbano", "Elegante", "Vintage", "Tradicional" }));
        FiltroTipo.setToolTipText("Filtrar");
        jPanel1.add(FiltroTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 130, 160, 31));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tipo de prenda");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 102, 160, 22));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Talla de la prenda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 171, 160, 22));

        FiltroTalla.setBackground(new java.awt.Color(153, 153, 153));
        FiltroTalla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroTalla.setForeground(new java.awt.Color(255, 255, 255));
        FiltroTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "S", "M", "L", "XS", "XL", "XXL", "XXXL", "Única", "36", "38", "40", "42", "44" }));
        FiltroTalla.setToolTipText("Filtrar");
        jPanel1.add(FiltroTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 199, 164, 31));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Material de la prenda");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 242, 160, 22));

        FiltroMaterial.setBackground(new java.awt.Color(153, 153, 153));
        FiltroMaterial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroMaterial.setForeground(new java.awt.Color(255, 255, 255));
        FiltroMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Algodón", "Seda", "Lino", "Poliéster", "Cuero", "Denim", "Lana", "Encaje", "Nylon", "Terciopelo", "Franela", "Rayón", "Spandex" }));
        FiltroMaterial.setToolTipText("Filtrar");
        jPanel1.add(FiltroMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 270, 164, 31));

        FiltroGenero.setBackground(new java.awt.Color(153, 153, 153));
        FiltroGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroGenero.setForeground(new java.awt.Color(255, 255, 255));
        FiltroGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Femenino", "Masculino", "Unisex", "Niño", "Niña", "Adolescente", "Maternidad", "Niño", "Niña", "Adolescente", "Maternidad" }));
        FiltroGenero.setToolTipText("Filtrar");
        jPanel1.add(FiltroGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 335, 164, 31));

        labelGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelGenero.setForeground(new java.awt.Color(255, 255, 255));
        labelGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGenero.setText("Genero de la prenda");
        jPanel1.add(labelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 307, 160, 22));

        FiltroCategoria.setBackground(new java.awt.Color(153, 153, 153));
        FiltroCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroCategoria.setForeground(new java.awt.Color(255, 255, 255));
        FiltroCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Vestido", "Camisa", "Pantalón", "Chaqueta", "Falda", "Blusa", "Short", "Abrigo", "Sudadera", "Traje de baño", "Overol", "Camiseta", "Chaleco" }));
        FiltroCategoria.setToolTipText("Filtrar");
        jPanel1.add(FiltroCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 400, 164, 31));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Categoria de la prenda");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 372, 160, 22));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        QuitarFiltros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QuitarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        QuitarFiltros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuitarFiltros.setText("QUITAR FILTROS");
        QuitarFiltros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitarFiltrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuitarFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuitarFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 580));

        jtPrendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPrendas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 1100, 400));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTADO DE PRENDAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1100, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAlquilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlquilarMouseClicked

        DefaultTableModel model = (DefaultTableModel) jtPrendas.getModel();

        List<String[]> prendasSeleccionadas = new ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            Boolean seleccionado = (Boolean) model.getValueAt(i, 0); // Columna del checkbox

            if (Boolean.TRUE.equals(seleccionado)) {
                String codigo = model.getValueAt(i, 1).toString();
                String color = model.getValueAt(i, 2).toString();
                String descripcion = model.getValueAt(i, 3).toString();
                String precio = model.getValueAt(i, 9).toString();
                String talla = model.getValueAt(i, 10).toString();

                prendasSeleccionadas.add(new String[]{codigo, descripcion, talla, color, precio});
            }
        }

        if (prendasSeleccionadas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No has seleccionado ninguna prenda.");
        } else {
            System.out.println(this.id);
            Alquiler a = new Alquiler(prendasSeleccionadas,this.id);
            a.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_BtnAlquilarMouseClicked

    private void BtnFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFiltroMouseClicked

        // Obtener los valores de los filtros (los convierte a null si son "Seleccione un tipo")
        String tipo = obtenerFiltro(FiltroTipo);
        String talla = obtenerFiltro(FiltroTalla);
        String material = obtenerFiltro(FiltroMaterial);
        String genero = obtenerFiltro(FiltroGenero);
        String categoria = obtenerFiltro(FiltroCategoria);

        // Verificar si todos son null
        if (tipo == null && talla == null && material == null && genero == null && categoria == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un filtro para realizar la búsqueda.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            // Al menos uno se seleccionó: cargar los productos filtrados
            System.out.println(tipo+","+ talla+","+ material+","+ genero+","+ categoria);
            jtPrendas.setModel(prodContoller.cargarProductos(categoria, genero, material, tipo, talla));
            
        }
    }//GEN-LAST:event_BtnFiltroMouseClicked

    private void QuitarFiltrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitarFiltrosMouseClicked
        jtPrendas.setModel(prodContoller.cargarProductos(null, null, null, null, null));
    }//GEN-LAST:event_QuitarFiltrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAlquilar;
    private javax.swing.JLabel BtnFiltro;
    private javax.swing.JPanel BtnFiltros;
    private javax.swing.JComboBox<String> FiltroCategoria;
    private javax.swing.JComboBox<String> FiltroGenero;
    private javax.swing.JComboBox<String> FiltroMaterial;
    private javax.swing.JComboBox<String> FiltroTalla;
    private javax.swing.JComboBox<String> FiltroTipo;
    private javax.swing.JLabel QuitarFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPrendas;
    private javax.swing.JLabel labelGenero;
    // End of variables declaration//GEN-END:variables
}
