/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package humanizar.alquilerprendas.view;

import humanizar.alquilerprendas.Service.EntityService;
import humanizar.alquilerprendas.controller.LoginController;
import humanizar.alquilerprendas.controller.PrendaController;
import humanizar.alquilerprendas.controller.ProductoController;
import humanizar.alquilerprendas.facade.PrendaFacade;
import humanizar.alquilerprendas.model.Categoria;
import humanizar.alquilerprendas.model.Genero;
import humanizar.alquilerprendas.model.Material;
import humanizar.alquilerprendas.model.Talla;
import humanizar.alquilerprendas.model.Tipo;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Santos
 */
public class homeEmpleadoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ProductoController prodContoller = new ProductoController();
    public int id;

    public homeEmpleadoAdmin(int idUser) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.id = idUser;
    }

    public String obtenerFiltro(JComboBox combo) {
        Object item = combo.getSelectedItem();
        if (item != null && !item.toString().equalsIgnoreCase("Seleccione un tipo")) {
            return item.toString();
        }
        return null;
    }

    LoginController login = new LoginController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Contrasenia = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        Salario = new javax.swing.JTextField();
        Cargo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCrearEmpleado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        FiltroCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        FiltroGenero = new javax.swing.JComboBox<>();
        FiltroMaterial = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        FiltroTalla = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        FiltroPedreria = new javax.swing.JComboBox<>();
        FiltroTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        Color = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCrearPrenda = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 350));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 10, 520));

        Direccion.setBackground(new java.awt.Color(153, 153, 153));
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Direccion.setMaximumSize(new java.awt.Dimension(65, 40));
        Direccion.setMinimumSize(new java.awt.Dimension(65, 40));
        Direccion.setPreferredSize(new java.awt.Dimension(65, 40));
        jPanel2.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 259, 51));

        telefono.setBackground(new java.awt.Color(153, 153, 153));
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telefono.setMaximumSize(new java.awt.Dimension(65, 40));
        telefono.setMinimumSize(new java.awt.Dimension(65, 40));
        telefono.setPreferredSize(new java.awt.Dimension(65, 40));
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        jPanel2.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 260, 51));

        Email.setBackground(new java.awt.Color(153, 153, 153));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Email.setMaximumSize(new java.awt.Dimension(65, 40));
        Email.setMinimumSize(new java.awt.Dimension(65, 40));
        Email.setPreferredSize(new java.awt.Dimension(65, 40));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 259, 51));

        Contrasenia.setBackground(new java.awt.Color(153, 153, 153));
        Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        Contrasenia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Contrasenia.setMaximumSize(new java.awt.Dimension(65, 40));
        Contrasenia.setMinimumSize(new java.awt.Dimension(65, 40));
        Contrasenia.setPreferredSize(new java.awt.Dimension(65, 40));
        Contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseniaActionPerformed(evt);
            }
        });
        jPanel2.add(Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 260, 51));

        Cedula.setBackground(new java.awt.Color(153, 153, 153));
        Cedula.setForeground(new java.awt.Color(255, 255, 255));
        Cedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Cedula.setMaximumSize(new java.awt.Dimension(65, 40));
        Cedula.setMinimumSize(new java.awt.Dimension(65, 40));
        Cedula.setPreferredSize(new java.awt.Dimension(65, 40));
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        jPanel2.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 260, 51));

        Salario.setBackground(new java.awt.Color(153, 153, 153));
        Salario.setForeground(new java.awt.Color(255, 255, 255));
        Salario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Salario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Salario.setMaximumSize(new java.awt.Dimension(65, 40));
        Salario.setMinimumSize(new java.awt.Dimension(65, 40));
        Salario.setPreferredSize(new java.awt.Dimension(65, 40));
        Salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioActionPerformed(evt);
            }
        });
        Salario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalarioKeyTyped(evt);
            }
        });
        jPanel2.add(Salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 260, 51));

        Cargo.setBackground(new java.awt.Color(153, 153, 153));
        Cargo.setForeground(new java.awt.Color(255, 255, 255));
        Cargo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Cargo.setMaximumSize(new java.awt.Dimension(65, 40));
        Cargo.setMinimumSize(new java.awt.Dimension(65, 40));
        Cargo.setPreferredSize(new java.awt.Dimension(65, 40));
        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });
        jPanel2.add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 260, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PANEL ADMINISTRADOR");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 2, 1120, 53));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrar Empleado");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 76, 590, 30));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 600, 40));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCrearEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearEmpleado.setText("CREAR EMPLEADO");
        btnCrearEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearEmpleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 220, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrar Prenda");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 590, 40));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 590, 40));

        Nombre.setBackground(new java.awt.Color(153, 153, 153));
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Nombre.setMaximumSize(new java.awt.Dimension(65, 40));
        Nombre.setMinimumSize(new java.awt.Dimension(65, 40));
        Nombre.setPreferredSize(new java.awt.Dimension(65, 40));
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 260, 50));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Descripcion.setBackground(new java.awt.Color(153, 153, 153));
        Descripcion.setColumns(20);
        Descripcion.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion.setRows(5);
        Descripcion.setBorder(null);
        jScrollPane1.setViewportView(Descripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 230, 230));

        FiltroCategoria.setBackground(new java.awt.Color(153, 153, 153));
        FiltroCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroCategoria.setForeground(new java.awt.Color(255, 255, 255));
        FiltroCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Vestido", "Camisa", "Pantalón", "Chaqueta", "Falda", "Blusa", "Short", "Abrigo", "Sudadera", "Traje de baño", "Overol", "Camiseta", "Chaleco" }));
        FiltroCategoria.setToolTipText("Filtrar");
        jPanel2.add(FiltroCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 260, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pedreria de la prenda");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 260, 40));

        labelGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelGenero.setForeground(new java.awt.Color(255, 255, 255));
        labelGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGenero.setText("Genero de la prenda");
        jPanel2.add(labelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 260, 40));

        FiltroGenero.setBackground(new java.awt.Color(153, 153, 153));
        FiltroGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroGenero.setForeground(new java.awt.Color(255, 255, 255));
        FiltroGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Femenino", "Masculino", "Unisex", "Niño", "Niña", "Adolescente", "Maternidad" }));
        FiltroGenero.setToolTipText("Filtrar");
        jPanel2.add(FiltroGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 260, 30));

        FiltroMaterial.setBackground(new java.awt.Color(153, 153, 153));
        FiltroMaterial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroMaterial.setForeground(new java.awt.Color(255, 255, 255));
        FiltroMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Algodón", "Seda", "Lino", "Poliéster", "Cuero", "Denim", "Lana", "Encaje", "Nylon", "Terciopelo", "Franela", "Rayón", "Spandex" }));
        FiltroMaterial.setToolTipText("Filtrar");
        jPanel2.add(FiltroMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 230, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Material de la prenda");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 230, 40));

        FiltroTalla.setBackground(new java.awt.Color(153, 153, 153));
        FiltroTalla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroTalla.setForeground(new java.awt.Color(255, 255, 255));
        FiltroTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "S", "M", "L", "XS", "XL", "XXL", "XXXL", "Única", "36", "38", "40", "42", "44" }));
        FiltroTalla.setToolTipText("Filtrar");
        jPanel2.add(FiltroTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Talla de la prenda");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 230, 40));

        FiltroPedreria.setBackground(new java.awt.Color(153, 153, 153));
        FiltroPedreria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroPedreria.setForeground(new java.awt.Color(255, 255, 255));
        FiltroPedreria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Si", "No" }));
        FiltroPedreria.setToolTipText("Filtrar");
        jPanel2.add(FiltroPedreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 260, 30));

        FiltroTipo.setBackground(new java.awt.Color(153, 153, 153));
        FiltroTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FiltroTipo.setForeground(new java.awt.Color(255, 255, 255));
        FiltroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Casual", "Formal", "Deportivo", "Fiesta", "Boda", "Trabajo", "Playa", "Invierno", "Verano", "Urbano", "Elegante", "Vintage", "Tradicional" }));
        FiltroTipo.setToolTipText("Filtrar");
        jPanel2.add(FiltroTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 230, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tipo de prenda");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 230, 40));

        Precio.setBackground(new java.awt.Color(153, 153, 153));
        Precio.setForeground(new java.awt.Color(255, 255, 255));
        Precio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Precio.setMaximumSize(new java.awt.Dimension(65, 40));
        Precio.setMinimumSize(new java.awt.Dimension(65, 40));
        Precio.setPreferredSize(new java.awt.Dimension(65, 40));
        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });
        Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioKeyTyped(evt);
            }
        });
        jPanel2.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 260, 51));

        Color.setBackground(new java.awt.Color(153, 153, 153));
        Color.setForeground(new java.awt.Color(255, 255, 255));
        Color.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Color.setMaximumSize(new java.awt.Dimension(65, 40));
        Color.setMinimumSize(new java.awt.Dimension(65, 40));
        Color.setPreferredSize(new java.awt.Dimension(65, 40));
        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });
        jPanel2.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 260, 51));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Categoria de la prenda");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 260, 40));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCrearPrenda.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearPrenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearPrenda.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPrenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearPrenda.setText("CREAR PRENDA");
        btnCrearPrenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPrendaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearPrenda, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearPrenda, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 490, -1, -1));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setToolTipText("Salir");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("SALIR");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed

    }//GEN-LAST:event_telefonoActionPerformed

    private void telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyPressed

    }//GEN-LAST:event_telefonoKeyPressed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        char c = evt.getKeyChar();

        // Permitir solo dígitos, borrar (backspace) y suprimir (delete)
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            getToolkit().beep(); // Sonido de error
            evt.consume(); // Bloquea la tecla
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void ContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseniaActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void SalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioActionPerformed

    private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargoActionPerformed

    private void btnCrearEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoMouseClicked
        if (Nombre.getText().equals(null) || Nombre.getText().equals(" ") || Nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El nombre es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Direccion.getText().equals(null) || Direccion.getText().equals(" ") || Direccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La direccion es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Cedula.getText().equals(null) || Cedula.getText().equals(" ") || Cedula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La Cedula es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (telefono.getText().equals(null) || telefono.getText().equals(" ") || telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El telefono es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Email.getText().equals(null) || Email.getText().equals(" ") || Email.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El Email es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Contrasenia.getText().equals(null) || Contrasenia.getText().equals(" ") || Contrasenia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La Contraseña es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Salario.getText().equals(null) || Salario.getText().equals(" ") || Salario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El Salario es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Cargo.getText().equals(null) || Cargo.getText().equals(" ") || Cargo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La Cargo es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        } else {
            boolean validacion = login.Register(Nombre.getText(), Direccion.getText(), Cedula.getText(), telefono.getText(), Email.getText(), Contrasenia.getText(), 2, Cargo.getText(), Double.parseDouble(Salario.getText()));

            if (validacion) {
                Login form = new Login();
                form.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnCrearEmpleadoMouseClicked

    private void SalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalarioKeyTyped
        char c = evt.getKeyChar();

        // Permitir solo dígitos, borrar (backspace) y suprimir (delete)
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            getToolkit().beep(); // Sonido de error
            evt.consume(); // Bloquea la tecla
        }
    }//GEN-LAST:event_SalarioKeyTyped

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorActionPerformed

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    private void PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyTyped
        char c = evt.getKeyChar();

        // Permitir solo dígitos, borrar (backspace) y suprimir (delete)
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            getToolkit().beep(); // Sonido de error
            evt.consume(); // Bloquea la tecla
        }
    }//GEN-LAST:event_PrecioKeyTyped
    private PrendaController prendaController = new PrendaController(new PrendaFacade());
    private void btnCrearPrendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPrendaMouseClicked

        String tipoStr = obtenerFiltro(FiltroTipo);
        String tallaStr = obtenerFiltro(FiltroTalla);
        String materialStr = obtenerFiltro(FiltroMaterial);
        String generoStr = obtenerFiltro(FiltroGenero);
        String categoriaStr = obtenerFiltro(FiltroCategoria);
        String pedreriaStr = obtenerFiltro(FiltroPedreria);

        EntityService en = new EntityService();
        Tipo tipo = en.buscarTipoPorNombre(tipoStr);
        Talla talla = en.buscarTallaPorNombre(tallaStr);
        Material material = en.buscarMaterialPorNombre(materialStr);
        Genero genero = en.buscarGeneroPorNombre(generoStr);
        Categoria categoria = en.buscarCategoriaPorNombre(categoriaStr);
        boolean pedreria = "si".equalsIgnoreCase(pedreriaStr);

        if (tipo == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el tipo de prenda.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (talla == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la talla de la prenda.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (material == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el material de la prenda.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (genero == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el genero de prenda.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (categoria == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la categoria de la prenda.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (pedreriaStr == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar si la prenda tiene pedreria.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        if (Color.getText().equals(null) || Color.getText().equals(" ") || Color.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El color es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (Precio.getText().equals(null) || Precio.getText().equals(" ") || Precio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El Precio es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (Descripcion.getText().equals(null) || Descripcion.getText().equals(" ") || Descripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La Descripcion es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        Map<String, Object> parametros = new HashMap<>();
        parametros.put("tipo", tipo);
        parametros.put("talla", talla);
        parametros.put("material", material);
        parametros.put("genero", genero);
        parametros.put("categoria", categoria);
        parametros.put("pedreria", pedreria);
        parametros.put("color", Color.getText());
        parametros.put("precio", Double.parseDouble(Precio.getText()));
        parametros.put("descripcion", Descripcion.getText());

        boolean guardadoExitoso = prendaController.crearPrenda(parametros);
        if (guardadoExitoso) {
            JOptionPane.showMessageDialog(null, "Se a generado la prenda de manera exitosa", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error al generar la prenda", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnCrearPrendaMouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_label1MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cargo;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Color;
    private javax.swing.JTextField Contrasenia;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox<String> FiltroCategoria;
    private javax.swing.JComboBox<String> FiltroGenero;
    private javax.swing.JComboBox<String> FiltroMaterial;
    private javax.swing.JComboBox<String> FiltroPedreria;
    private javax.swing.JComboBox<String> FiltroTalla;
    private javax.swing.JComboBox<String> FiltroTipo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextField Salario;
    private javax.swing.JLabel btnCrearEmpleado;
    private javax.swing.JLabel btnCrearPrenda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
