/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package humanizar.alquilerprendas.view;

import humanizar.alquilerprendas.controller.AlquilerController;
import humanizar.alquilerprendas.controller.LoginController;
import humanizar.alquilerprendas.controller.ProductoController;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Santos
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ProductoController prodContoller = new ProductoController();
 public int id;
    public Inicio(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.id =id;
    }

    public String obtenerFiltro(JComboBox combo) {
        Object item = combo.getSelectedItem();
        if (item != null && !item.toString().equalsIgnoreCase("Seleccione un tipo")) {
            return item.toString();
        }
        return null;
    }

    LoginController login = new LoginController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NAlquiler = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrendas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BtnPorAlquiler = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnPorFecha = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        BtnAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 350));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAlquiler.setBackground(new java.awt.Color(153, 153, 153));
        NAlquiler.setForeground(new java.awt.Color(255, 255, 255));
        NAlquiler.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NAlquiler.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "número del alquiler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        NAlquiler.setMaximumSize(new java.awt.Dimension(65, 40));
        NAlquiler.setMinimumSize(new java.awt.Dimension(65, 40));
        NAlquiler.setPreferredSize(new java.awt.Dimension(65, 40));
        NAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAlquilerActionPerformed(evt);
            }
        });
        jPanel2.add(NAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 51));

        jtPrendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtPrendas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 950, 480));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnPorAlquiler.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnPorAlquiler.setForeground(new java.awt.Color(255, 255, 255));
        BtnPorAlquiler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnPorAlquiler.setText("Consultar");
        BtnPorAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPorAlquilerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnPorAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnPorAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 260, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONSULTA TUS SERVICIOS DE ALQUILER");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 2, 1280, 62));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnPorFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnPorFecha.setForeground(new java.awt.Color(255, 255, 255));
        BtnPorFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnPorFecha.setText("Consultar");
        BtnPorFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPorFechaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnPorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnPorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 260, 40));

        fecha.setBackground(new java.awt.Color(153, 153, 153));
        fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fecha.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 40));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAtras.setForeground(new java.awt.Color(255, 255, 255));
        BtnAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnAtras.setText("Retroceder");
        BtnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 260, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAlquilerActionPerformed

    private void BtnPorAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPorAlquilerMouseClicked
        // Solicitar el número de alquiler al usuario
        String input = NAlquiler.getText();

        // Convertir el input a entero
        try {
            Integer idServicio = Integer.parseInt(input.trim());

            // Crear instancia del controlador
            AlquilerController controller = new AlquilerController();

            // Mostrar los resultados en la tabla
            controller.mostrarAlquilerEnTabla(idServicio, jtPrendas);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese un número válido.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar el alquiler: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnPorAlquilerMouseClicked

    private void BtnPorFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPorFechaMouseClicked

        Date fechaSeleccionada = fecha.getDate();
        if (fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecciona una fecha válida.",
                    "Fecha no seleccionada",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        AlquilerController controller = new AlquilerController();
        boolean encontrado = controller.mostrarAlquileresPorFecha(fechaSeleccionada, jtPrendas);

        if (!encontrado) {
            // Ya se muestra un mensaje desde el controller, pero puedes hacer algo adicional aquí si quieres

        }
    }//GEN-LAST:event_BtnPorFechaMouseClicked

    private void BtnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtrasMouseClicked
        home form = new home(this.id);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAtras;
    private javax.swing.JLabel BtnPorAlquiler;
    private javax.swing.JLabel BtnPorFecha;
    private javax.swing.JTextField NAlquiler;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPrendas;
    // End of variables declaration//GEN-END:variables
}
