/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package humanizar.alquilerprendas.view;

import humanizar.alquilerprendas.controller.LoginController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Santos
 */
public class RegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarCliente() {
        initComponents();
    }
    LoginController login = new LoginController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Contrasenia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnRetroceder = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setBackground(new java.awt.Color(153, 153, 255));
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Nombre.setMaximumSize(new java.awt.Dimension(65, 40));
        Nombre.setMinimumSize(new java.awt.Dimension(65, 40));
        Nombre.setPreferredSize(new java.awt.Dimension(65, 40));
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 260, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese los siguientes datos ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        telefono.setBackground(new java.awt.Color(153, 153, 255));
        telefono.setForeground(new java.awt.Color(255, 255, 255));
        telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telefono.setMaximumSize(new java.awt.Dimension(65, 40));
        telefono.setMinimumSize(new java.awt.Dimension(65, 40));
        telefono.setPreferredSize(new java.awt.Dimension(65, 40));
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 260, 51));

        Direccion.setBackground(new java.awt.Color(153, 153, 255));
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Direccion.setMaximumSize(new java.awt.Dimension(65, 40));
        Direccion.setMinimumSize(new java.awt.Dimension(65, 40));
        Direccion.setPreferredSize(new java.awt.Dimension(65, 40));
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 259, 51));

        Email.setBackground(new java.awt.Color(153, 153, 255));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Email.setMaximumSize(new java.awt.Dimension(65, 40));
        Email.setMinimumSize(new java.awt.Dimension(65, 40));
        Email.setPreferredSize(new java.awt.Dimension(65, 40));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 259, 51));

        Contrasenia.setBackground(new java.awt.Color(153, 153, 255));
        Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        Contrasenia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Contrasenia.setMaximumSize(new java.awt.Dimension(65, 40));
        Contrasenia.setMinimumSize(new java.awt.Dimension(65, 40));
        Contrasenia.setPreferredSize(new java.awt.Dimension(65, 40));
        Contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 260, 51));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registrar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 190, 270));

        BtnRetroceder.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        BtnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetroceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnRetroceder.setText("RETROCEDER");
        BtnRetroceder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRetroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRetrocederMouseClicked(evt);
            }
        });
        jPanel1.add(BtnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 371, 160, 50));

        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnRegistrar.setText("REGISTRAR");
        BtnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 371, 140, 50));

        Cedula.setBackground(new java.awt.Color(153, 153, 255));
        Cedula.setForeground(new java.awt.Color(255, 255, 255));
        Cedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Cedula.setMaximumSize(new java.awt.Dimension(65, 40));
        Cedula.setMinimumSize(new java.awt.Dimension(65, 40));
        Cedula.setPreferredSize(new java.awt.Dimension(65, 40));
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        jPanel1.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 260, 51));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed

    }//GEN-LAST:event_telefonoActionPerformed

    private void telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyPressed

    }//GEN-LAST:event_telefonoKeyPressed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        char c = evt.getKeyChar();

        // Permitir solo dígitos, borrar (backspace) y suprimir (delete)
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            getToolkit().beep(); // Sonido de error
            evt.consume(); // Bloquea la tecla
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void ContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseniaActionPerformed

    private void BtnRetrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRetrocederMouseClicked
        Login form = new Login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRetrocederMouseClicked

    private void BtnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarMouseClicked

        if (Nombre.getText().equals(null) || Nombre.getText().equals(" ") || Nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El nombre es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Direccion.getText().equals(null) || Direccion.getText().equals(" ") || Direccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La direccion es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Cedula.getText().equals(null) || Cedula.getText().equals(" ") || Cedula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La Cedula es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (telefono.getText().equals(null) || telefono.getText().equals(" ") || telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El telefono es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Email.getText().equals(null) || Email.getText().equals(" ") || Email.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El Email es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        if (Contrasenia.getText().equals(null) || Contrasenia.getText().equals(" ") || Contrasenia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "La Contraseña es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);

        } else {
            boolean validacion = login.Register(Nombre.getText(), Direccion.getText(), Cedula.getText(), telefono.getText(), Email.getText(), Contrasenia.getText(), 1, "", 0);

            if (validacion) {
                Login form = new Login();
                form.setVisible(true);
                this.dispose();
            }
        }


    }//GEN-LAST:event_BtnRegistrarMouseClicked

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnRegistrar;
    private javax.swing.JLabel BtnRetroceder;
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Contrasenia;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
